package com.c24x7.formats;

import java.io.IOException;


import com.c24x7.nlservices.CNlOutputFormatter.AFormatProxy;
import com.c24x7.nlservices.content.CStructuredOutput;
import com.c24x7.clients.CFacebookClient;
import com.c24x7.util.logs.CLogger;
import com.c24x7.util.CXMLConverter;

	/**
	 * <p>Class used to convert a structured content generated by NLG engine into
	 * a facebook message.</p>
	 * @author Patrick Nicolas
	 * @date 11/28/2010
	 * @see com.c24x7.nlservices.CNlOutputFormatter.AFormatProxy
	 */

public final class CFacebookFormat extends AFormatProxy {
	private static String prevStatus = "x";
	
	private CFacebookClient _handle = null;
	private String		 	_status  = null;
	private String 		 	_link 	 = null;

	/**
	 * <p>Generates a Facebook message + link from a structured content generated by NLG engine</p>
	 * @param structuredOutput structured content generated by NLG engine
	 * @throws IllegalArgumentException if argument is null
	 */
	public void format(CStructuredOutput structuredOutput) throws IOException {
		if(structuredOutput == null) {
			throw new IllegalArgumentException("Structured Output is undefined!");
		}
		_error = null;
		
			/*
			 * Discard repeated or duplicate tweets..
			 */
		String newStatus = structuredOutput.getTitle().trim();
		System.out.println("Prev Facebook: " + prevStatus + "\nNew Facebook: " + newStatus);
		if(prevStatus.compareTo(newStatus) == 0) {
			_error = "Facebook message already sent!";
			_handle = null;
		}
		
		else {
			_status = newStatus;
			_link = "no link";
			if( _handle == null) {
				_handle = new CFacebookClient(_env);
				_head = "Account: " + _handle.getTarget();
			}
		
			/*
			 * If debug mode is selected then a file is generated
			 * to contain the duplicated message.
			 */
			debug(structuredOutput.toString(), "facebook/");
		}
	}
	

	
			/**
			 * <p>Build the results stream for the request to social network</p>
			 * @return String to be streamed back to the front-end processor
			 */
	public String results() {
		StringBuilder buf = new StringBuilder();
		
		if (_error == null) {
			buf.append( CXMLConverter.put(CXMLConverter.HEAD_TAG, _head) );
			buf.append( CXMLConverter.put(CXMLConverter.STATUS_TAG, _status) );
			buf.append( CXMLConverter.put(CXMLConverter.LINK_TAG, _link) );
		}
		else {
			buf.append(CXMLConverter.put(CXMLConverter.ERROR_TAG, _error));
		}

		return CXMLConverter.put(CXMLConverter.FACEBOOK_TAG, buf.toString());
	}
	
			
			/**
			 * <p>Process the request to the social network target site.
			 * The process is executed within a separate thread.</p>
			 */
	protected void process() { 
		try {
			if( _handle != null ) {
				_handle.update(_status);
				prevStatus = _status;
			}
		}
		catch( IOException e) {
			_error = "Facebook status update failed!";
			CLogger.error("Facebook processing error:" + _error);
		}
	}
}

// --------------------------------  EOF ---------------------------------------