// Copyright (C) 2010-2012 Patrick Nicolas
package com.c24x7.formats;

import java.io.IOException;


import com.c24x7.clients.facebook.CFacebookPut;
import com.c24x7.formats.CFormatter.AFormatProxy;
import com.c24x7.util.string.CXMLConverter;



	/**
	 * <p>Class used to convert a structured content generated by NLG engine into
	 * a facebook message.</p>
	 * @author Patrick Nicolas
	 * @date 11/28/2010
	 * @see com.c24x7.nlservices.CNlOutputFormatter.AFormatProxy
	 */

public final class CFacebookFormat extends AFormatProxy {
	protected CFacebookPut _handle = null;

	
	public AFormatProxy create() {
		return new CFacebookFormat();
	}
	
	
	/**
	 * <p>Generates a Facebook message + link from a structured content generated by NLG engine</p>
	 * @param structuredOutput structured content generated by NLG engine
	 * @throws IllegalArgumentException if argument is null
	 */
	public void createMsg(CExtractor extractor) throws IOException  {
		if( _handle == null) {
		//	_handle = new CFacebookPut();
		//	_head = "Account: " + _handle.getTarget();
		}
	}
	

	
			/**
			 * <p>Build the results stream for the request to social network</p>
			 * @return String to be streamed back to the front-end processor
			 */
	public String results() {
		StringBuilder buf = new StringBuilder();
		
		if (_error == null) {
			buf.append( CXMLConverter.put(CXMLConverter.HEAD_TAG, _head) );
			buf.append( CXMLConverter.put(CXMLConverter.STATUS_TAG, _msg) );
			buf.append( CXMLConverter.put(CXMLConverter.LINK_TAG, _link) );
		}
		else {
			buf.append(CXMLConverter.put(CXMLConverter.ERROR_TAG, _error));
		}

		return CXMLConverter.put(CXMLConverter.FACEBOOK_TAG, buf.toString());
	}
	
	
	protected void extractMessage(CExtractor extractor) {
		_msg = extractor.getFacebookStatus(_link);
	}
}

// --------------------------------  EOF ---------------------------------------