package com.c24x7.formats;

import java.io.IOException;

import com.c24x7.nlservices.CNlOutputFormatter.AFormatProxy;
import com.c24x7.nlservices.content.CStructuredOutput;
import com.c24x7.util.logs.CLogger;
import com.c24x7.util.CXMLConverter;
import com.c24x7.clients.CMailClient;


		/**
		 * <p>Nested class that format generated content for email through SMTP and SMTP+SSL protocol.</p>
		 * @author Patrick Nicolas
		 * @date 12/07/2010
		 */
public final class CMailFormat extends AFormatProxy {
	private static String prevSubject = "x";
	
	private CMailClient _handle = null;
	private String		_subject = null;
	private String		_body  = null;
	private String		_to	   = null;

		/**
		 * <p>Construct an email message from the output generated from the NLG engine</p>
		 * @param structuredOutput structured content generated by NLG engine
		 * @throws IllegalArgumentException if argument is null
		 * @throws IOException if content cannot be retrieved
		 */
	public void format(CStructuredOutput structuredOutput) throws IOException {
		if(structuredOutput == null) {
			throw new IllegalArgumentException("Structured Output is undefined!");
		}
		
		String newSubject = structuredOutput.getTitle().trim();
		if(prevSubject.compareTo(newSubject) == 0) {
			_error = "Email message already sent!";
			_handle = null;
		}
		else {
			if( _handle == null) {
				_handle = new CMailClient(_env);
			}
		
			_head = _handle.getUserName();
			_subject = new String(structuredOutput.getTitle());
			_body = new String(structuredOutput.getDescription());
			_to = new String(_handle.getToListString());
		
			debug(structuredOutput.toString(), "mail/");
		}
	}

	


	
	/**
	 * <p>Build the results stream for the request to social network</p>
	 * @return String to be streamed back to the front-end processor
	 */

	public String results() {
		StringBuilder buf = new StringBuilder();
		if (_error == null) {
			buf.append( CXMLConverter.put(CXMLConverter.HEAD_TAG, _head) );
			buf.append( CXMLConverter.put(CXMLConverter.TO_TAG, _to) );
			buf.append( CXMLConverter.put(CXMLConverter.SUBJECT_TAG, _subject) );
			buf.append( CXMLConverter.put(CXMLConverter.BODY_TAG, _body) );
		}
		else {
			buf.append(CXMLConverter.put(CXMLConverter.ERROR_TAG, _error));
		}

		return CXMLConverter.put(CXMLConverter.EMAIL_TAG, buf.toString());
	}
	
	/**
	 * <p>Process the request to the social network target site.
	 * The process is executed within a separate thread.</p>
	 */
	protected void process() {
		try {
			if (_handle != null) {
				_handle.setSubject(_subject);
				_handle.update(_body);
				prevSubject = _subject;
			}
		}
		catch(IOException e) {
			_error = "Failed sending email" + e.toString();
			CLogger.error("Email processing error:" + _error);
		}
	}

}

// -------------------------------------- EOF ---------------------------