// Copyright (C) Patrick Nicolas 2011
package com.c24x7.formats;

import java.io.IOException;
import com.c24x7.clients.rss.CRSSGenerator;
import com.c24x7.formats.CFormatter.AFormatProxy;


/**
 * <p>RSS format used to convert a structured content generated by NLG engine into
 * a RSS feed.</p>
 * @author Patrick Nicolas
 * @date 11/24/2010
 * @see com.c24x7.nlservices.CNlOutputFormatter.NFormat
 */
public final class CRSSFormat extends AFormatProxy {
	protected CRSSGenerator _rssGen = null;

	/**
	 * <p>Initialize the RSS formatting with a RSS generator object</p>
	 * @param rssGen RSS feed generator
	 */
	public void setGenerator(CRSSGenerator rssGen) {
		if( rssGen == null ) {
			throw new IllegalArgumentException("Rss Generator undefined!");
		}
		_rssGen = rssGen;
	}
	
	public AFormatProxy create() {
		return new CRSSFormat();
	}
	

		/**
		 * <p>Generates a RSS feed from a structured content generated by a NLG engine</p>
		 * @param structuredOutput structured content generated by NLG engine
		 * @throws IllegalArgumentException if argument is null
		 */

	public void createMsg(CExtractor extractor) throws IOException  {
	}


	protected void extractMessage(CExtractor extractor) {
	}


	/**
	 * <p>Build the results stream for the request to social network</p>
	 * @return String to be streamed back to the front-end processor
	 */

	public String results() {
		return "";
	}
	
	/**
	 * <p>Process the request to the social network target site.
	 * The process is executed within a separate thread.</p>
	 */
	/*
	protected void process() {
		try {
			_rssGen.create();
		}
		catch( XMLStreamException e ) {
			_error = e.toString();
			CLogger.error(e.toString());
		}
		catch( FileNotFoundException e) {
			_error = e.toString();
			CLogger.error(e.toString());
		}
	}
	*/
}

// ------------------------------------  EOF --------------------------------