// Copyright 2010-2011 Patrick Nicolas
package com.c24x7.formats;

import java.io.IOException;

import com.c24x7.clients.twitter.CTwitterPut;
import com.c24x7.formats.CFormatter.AFormatProxy;
import com.c24x7.util.string.CXMLConverter;




/**
 * <p>Format the generated output as a tweet. Select the closest sentence or summary about the content.
 * to fit into a Tweet. The excess of the content generated is 
 * loaded into a page/link.</p>
 * @author Patrick Nicolas
 * @date 11/28/2010
 * @see com.c24x7.nlservices.CNlOutputFormatter.ATargetProxy
 */
public final class CTwitterFormat extends AFormatProxy {

	protected CTwitterPut 	_handle = null;

		/**
		 * <p>Generates a output content formatted for Twitter from a list of generated sentences (NLG)</p>
		 * @param structuredOutput structured content generated by NLG engine
		 * @throws IllegalArgumentException if argument is null
		 * @throws IOException if generated content cannot be retrieved.
		 */
	public void createMsg(CExtractor extractor) {
		if( _handle == null) {
			_handle = new CTwitterPut();
		}
	}

	
	
	public AFormatProxy create() {
		return new CTwitterFormat();
	}
	
	/**
	 * <p>Build the results stream for the request to social network</p>
	 * @return String to be streamed back to the front-end processor
	 */

	public String results() {
		StringBuilder buf = new StringBuilder();
		if(_error == null) {
			buf.append( CXMLConverter.put(CXMLConverter.HEAD_TAG, _head) );
			buf.append( CXMLConverter.put(CXMLConverter.TWEET_TAG, _msg) );
			buf.append( CXMLConverter.put(CXMLConverter.LINK_TAG, _link) );
		}
		else {
			buf.append( CXMLConverter.put(CXMLConverter.ERROR_TAG, _error) );
		}
		return CXMLConverter.put(CXMLConverter.TWITTER_TAG, buf.toString());
	}


	/**
	 * <p>Process the request to the social network target site.
	 * The process is executed within a separate thread.</p>
	 */
	/*(
	protected void process() {
		try {
			if( _handle != null ) {
				_handle.update(_msg);
				old = _msg;
			}
		}
		catch( IOException e) {
			_error = "Error processing " + _head;
			CLogger.error("Twitter Error:" + e.toString());
		}
	}
	*/
	protected void extractMessage(CExtractor extractor) {	
		_msg = extractor.getTweet(_link);
	}
}
// -------------------------------  EOF -----------------------------------
