// Copyright 2010-2011 Patrick Nicolas
package com.c24x7.formats;

import java.io.IOException;

import com.c24x7.util.CEnv;
import com.c24x7.util.logs.CLogger;
import com.c24x7.util.string.CXMLConverter;
import com.c24x7.clients.CFTPClient;
import com.c24x7.formats.CFormatter.AFormatProxy;



/**
 * <p>Generate content for a full or partial update of a web page.
 * The web filter relies on the maximum number of character, the target
 * URL and optionally the id of a DOM element to be updated..</p>
 * @author Patrick Nicolas
 * @date 11/28/2010
 * @see com.c24x7.nlservices.CNlOutputFormatter.AFormatProxy
 */
public final class CWebFormat extends AFormatProxy {
	protected CFTPClient _handle 	  = null;
	protected String	   _inputFile = null;
	protected String	   _body	  = null;

	
	public AFormatProxy create() {
		return new CWebFormat();
	}
	
	
		/**
		 * <p>If there is no id attached to the generated content,
		 * it will be inserted into a new page, otherwise extract a div
		 * component from the ID and insert the new content.</p>
		 * @param structuredOutput structured content generated by NLG engine
		 * @throws IllegalArgumentException if argument is null
		 * @throws IOException if content cannot be retrieved
		 */
	public void createMsg(CExtractor extractor) throws IOException  {	

			/*
			 * Create the input FTP file
			 */
		_inputFile = CLogger.createFileName(CEnv.localftpDir, "ftp_", "html");
	//		_body = newPost;
		
	//	write(_inputFile,  CConvertToHTML.convert("demo", _msg, _body, null));
	
		if( _handle == null) {
			_handle= new CFTPClient("demo");
			_head = _handle.getUrlStr();
		}
	}
	
	protected void extractMessage(CExtractor extractor) {
	}



	/**
	 * <p>Build the results stream for the request to social network</p>
	 * @return String to be streamed back to the front-end processor
	 */

	public String results() {
		StringBuilder buf = new StringBuilder();
		if( _error == null ) {
			buf.append( CXMLConverter.put(CXMLConverter.HEAD_TAG, _head) );
			buf.append( CXMLConverter.put(CXMLConverter.TITLE_TAG, _msg) );
			buf.append( CXMLConverter.put(CXMLConverter.BODY_TAG, _body) );
		}
		else {
			buf.append(CXMLConverter.put(CXMLConverter.ERROR_TAG, _error));
		}

		return CXMLConverter.put(CXMLConverter.WEB_TAG, buf.toString());
	}
	
	/**
	 * <p>Process the request to the social network target site.
	 * The process is executed within a separate thread.</p>
	 */
	/*
	protected void process() {
		try {
			_handle.update(_inputFile);
		}
		catch( IOException e) {
			_error = e.toString();
			CLogger.error("Web processing error:" + _error);
		}
	}
	*/
}


// ------------------------------  EOF ----------------------------
